## 아다마르 곱 (Hadamard Product)

### 개념
아다마르 곱은 두 텐서의 원소별 곱을 의미합니다. 이는 두 텐서의 대응하는 위치의 원소를 곱한 결과를 포함하는 텐서를 반환합니다. 아다마르 곱은 동일한 형태(shape)를 가진 두 텐서에 대해 수행됩니다.

### 수식
두 텐서 $\(\mathbf{A}\)$와 $\(\mathbf{B}\)$가 주어졌을 때, 아다마르 곱 $\(\mathbf{C}\)$는 다음과 같이 정의됩니다

$$
\mathbf{C}_{ij} = \mathbf{A}_{ij} \cdot \mathbf{B}_{ij}
$$

### 예시
$$
\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

$$
\mathbf{B} = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

$$
아마다르 곱 \mathbf{C} = \begin{bmatrix} 1 \cdot 5 & 2 \cdot 6 \\ 3 \cdot 7 & 4 \cdot 8 \end{bmatrix} = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix}
$$


<br>

### 용도
- **요소별 연산**: 신경망에서 활성화 함수와 같이 요소별로 연산을 수행할 때 사용됩니다.
- **특징 조합**: 두 가지 특징을 결합하여 새로운 특징을 만들 때 사용됩니다. 예를 들어, 두 이미지의 픽셀별 곱 등을 계산할 때.
- **가중치 적용**: 특정 가중치를 각 원소에 개별적으로 적용할 때 사용됩니다.


In [5]:
import torch
import numpy as np
import tensorflow as tf

In [6]:
# PyTorch
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

a * b

tensor([[ 5, 12],
        [21, 32]])

In [7]:
# Tensorflow
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [8]:
# Numpy
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.multiply(a, b)

array([[ 5, 12],
       [21, 32]])

## 텐서 리덕션 (Tensor Reduction)

텐서 리덕션은 다차원 텐서를 하나 또는 더 낮은 차원의 텐서로 변환하는 연산입니다. 

이 과정에서 텐서의 원소들에 대해 특정 연산을 수행하여 차원을 축소합니다. 일반적으로 사용되는 리덕션 연산에는 합(sum), 평균(mean), 최대(max) 등이 있습니다.

<br>

### 주요 리덕션 연산

- 합(sum): 텐서의 모든 원소를 더하여 스칼라 값을 반환하거나, 특정 축을 따라 원소를 더하여 차원을 줄입니다.
- 평균(mean): 텐서의 모든 원소의 평균을 계산하여 스칼라 값을 반환하거나, 특정 축을 따라 원소의 평균을 계산하여 차원을 줄입니다.
- 최대(max): 텐서의 모든 원소 중 최대값을 반환하거나, 특정 축을 따라 최대값을 찾아 차원을 줄입니다.

<br>

### 용도

- 특징 요약: 대규모 데이터에서 중요한 특징을 요약할 때 사용됩니다. 예를 들어, 이미지 데이터에서 각 채널의 평균값을 구하는 등.
- 손실 계산: 머신러닝 모델의 손실 함수를 계산할 때 사용됩니다. 예를 들어, 예측 값과 실제 값의 차이의 합을 구하는 것 등.

In [9]:
# PyTorch
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
result = torch.sum(tensor)

result

tensor(21)

In [10]:
# Tensorflow
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
result = tf.reduce_mean(tensor)

result

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
# Numpy
tensor = np.array([[1, 2, 3], [4, 5, 6]])

np.max(tensor)

6