## 텐서의 전치와 기초 연산

### 텐서의 전치

텐서의 전치는 행렬의 전치와 유사하게 텐서의 축을 교환하는 연산이며, 기초 연산에는 덧셈, 뺄셈, 곱셈, 나눗셈 등 매우 쉽게 연산을 할 수 있습니다.

#### 예시: PyTorch

In [2]:
import torch

# Pytorch 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 텐서 전치
transposed_tensor = tensor.t()
transposed_tensor

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [3]:
# 더하기
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

a+b

tensor([5, 7, 9])

#### 예시: Tensorflow

In [4]:
import tensorflow as tf

# Tensorflow 텐서 생성
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# 텐서 전치
transposed_tensor = tf.transpose(tensor)
transposed_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [5]:
# 곱하기
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

#### 예시: Numpy

In [6]:
import numpy as np

# Numpy 텐서 생성
tensor = np.array([[1, 2, 3], [4, 5, 6]])

# 텐서 전치
transposed_tensor = np.transpose(tensor)
transposed_tensor

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
# 나누기
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a/b

array([0.25, 0.4 , 0.5 ])