## Vector

1차원 텐서인 벡터는 수의 1차원 배열이며, 순서를 이뤄 정렬되어 있고, Italic, Bold체로 표기됩니다. (Scala는 Italic으로만 표기)

벡터내 모든 요소는 특정 순서를 가지며, 각 요소는 인덱스를 이용해 접근 가능하고 각 요소는 Italic체의 Scala로 구성됩니다.

만약 어떤 x라는 벡터의 두번째 인덱스를 적고자 한다면 x는 Bold, x2는 Italic으로 표기됩니다.

또한 벡터를 이용해 공간 내의 좌표뿐 아니라 공간에 걸친 특정 규모나 방향을 표현할 수 있습니다.

In [21]:
import numpy as np

x = np.array([25, 2, 5]) # 타입 선언 생략 -> 정수형 ex) np.array([25, 2, 5], dtype=np.float16)

In [22]:
len(x) # 길이 확인

3

In [23]:
x.shape # 차원 확인

(3,)

In [24]:
type(x) # 타입 확인

numpy.ndarray

In [25]:
x[0] # 요소 접근

25

In [26]:
type(x[0]) # 넘파이 배열의 요소 타입 확인

numpy.int32

## Vector Transposition (벡터 전치)

벡터에서 전치란 열벡터를 전치하면 행벡터가 되고 행백테를 전치하면 열벡터가 되는 개념입니다.

따라서 벡터내 모든 요소가 변함없이 전치되고 순서도 그대로 유지됩니다.

만약 row vector(1,3)이 column vector로 전치해서 shape 해보면 (1,3) -> (3,1)로 변환됩니다.

### x의 전치

위에 선언한 x의 전치인 x.T를 x_t에 대입해서 shape를 해보면 변화가 없다.

왜냐하면 보통 넘파이의 1차원 배열은 대괄호로 구체화되기 떄문이다.

따라서 이를 전치하면 1 혹인 2 등의 전치를 시켜줄 "차원" 자체가 없게 된다.

In [27]:
# 차원의 변화가 없는 전치 대입
x_t = x.T
x_t

array([25,  2,  5])

In [28]:
x_t.shape

(3,)

위 문제를 해결하려면 넘파이 배열을 생성할떄 중첩 행렬(matrix) 스타일로 [[]] 선언을 해주고 전치를 하면,

그제서야 y 벡터는 2개의 차원을 가지는 (1,3) 2차원 텐서인 벡터가 생성됩니다.

아래 y를 전치해보면 기존 (1,3)에서 (3,1)로 잘 변환된걸 볼 수 있습니다.

In [29]:
# 2차원 텐서 생성
y = np.array([[25, 2, 5]])

In [30]:
y.shape

(1, 3)

In [31]:
# 열벡터를 행벡터로 전치
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [32]:
y_t.shape

(3, 1)

In [33]:
# 행벡터를 다시 열벡터도 전치
y_t.T

array([[25,  2,  5]])

In [34]:
y_t.T.shape

(1, 3)

## Zero Vector

0 벡터란 벡터의 값이 모두 0인것을 의미하며, 이 0 벡터는 넘파이의 `np.zeros()`로 생성할 수 있고, 텐서의 차원도 구체화 가능합니다.

In [35]:
# 1차원 3의 크기를 가지는 텐서 생성
z = np.zeros(3)
z

array([0., 0., 0.])

## Vector in Pytorch and Tensorflow

Pytorch와 Tensorflow에서 벡터를 생성할때도 넘파이에서와 같이 구체화 해주면 됩니다.

In [36]:
import torch
import tensorflow as tf

In [37]:
# Pytorch Tensor
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [38]:
# Tensorflow Tensor
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>