## Norm & Unit Vector

이번에는 주어진 벡터를 이용해 어떻게 공간에 걸친 규모와 방향을 표현하는지와,

벡터의 규모를 수량화하는 클래스 함수인 노름과 단위 벡터에 대해 알아보겠습니다.

<br>

지난번엔 벡터의 어떤 공간 내 좌표와 그 크기 표현에 대한걸 학습하였습니다.

예를 들면, `[x1, x2] = [12, 4]` 벡터가 그래프상의 어떤 x,y 값의 교차점(좌표)로도 활용되고 이건 출발점 혹은 그 원형으로부터의 규모나 방향을 나타낼 수도 있습니다.

위의 경우는 벡터가 0,0 이라는 공간으로부터 12,4 좌표까지의 흔적을 남기는 것이죠.

<br>

모든 노름 함수 중에서 가장 흔하고 중요한 함수는 L2 노름입니다.

L1 노름은 **각 성분의 변화량의 절대값을 모두 더하는** 방식이며,

L2 노름은 **피타고라스 정리에 의한 유클리드 거리(최단)** 을 계산하는 방식(0벡터로부터 간단한 거리 계산)입니다.

벡터 x의 노름 기호 : **$||x||$**

<br>

L2 노름은 벡터 내 각 요소를 제곱한 후 모든 요소를 다시 더해주고 시그마의 총합에 제곱근을 씌워 값을 구합니다.

In [7]:
import numpy as np
import tensorflow as tf

x = np.array([25, 2, 5])

## $L^2$ Norm

파티고라스 정리에 의한 유클리드 거리(최단 / 0벡터로부터 간단한 거리) 계산

![](./2.png)

In [8]:
# 위에서 생성한 벡터 x
x

array([25,  2,  5])

In [9]:
# 각 벡터의 요소를 제곱하고 전부다 더한다음 그 합의 제곱근 구하기
# 0벡터부터 [25,2,5] 까지의 거리
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [10]:
# Numpy의 norm()을 사용해 위 과정을 단순화 하기
np.linalg.norm(x)

25.573423705088842

만약 3차원 공간 내 개체가 미터(m)일 경우 이 벡터 x는 0벡터부터의 거리나 크기를 의미합니다. -> 25.6m

## $L^1$ Norm

각 성분의 변화량의 절대값을 모두 더하는 방식이며, 머신러닝에 자주 사용됩니다.

L1 노름이 가지는 흥미로운 특성 중 하나는 이 노름이 0벡터에서의 거리와 상관없이 선형을 띄며, 0과 0이 아닌 것들 사이의 차이점이 중요한 곳에서 사용됩니다.

![](./1.png)

In [11]:
# 위에서 생성한 벡터 x
x

array([25,  2,  5])

In [12]:
# 각 요소의 절대값의 합을 구하는 방식
np.abs(25) + np.abs(2) + np.abs(5)

32

## Squared $L^2$ Norm

제곱 L2 노름은 마지막 단계만 뺴면 L2 노름과 유사합니다.

마지막 단계란 기존 L2 노름에서 각 요소의 제곱을 전부 더해주고 거기에 루트값을 취해주었는데,

제곱 L2 노름은 **루트값을 취하는 과정이 빠진** 함수입니다.

* 흔히 쓰이는 L2 노름에 비하면 연산적으로 훨씬 저비용인 함수이며, 이 노름의 도함수는 많은 머신러닝 알고리즘을 학습시킬 때 사용
* 제곱 L2노름은 간단하게 `전치된 x`에 `x`를 곱한 값과 같습니다. 그래서 매우 간단하고 저비용
* 단독 요소 x의 도함수가 그 요소 하나만을 요구함, L2 노름에서 벡터 전체의 정보가 필요한것에 대비됨
* 제곱 L2 노름의 결점은 0벡터에서 아주 느리게 자람
* 따라서 0과 0과 가까운 값이 중요한 정보일떄 그 값을 구별할 수 없음

In [13]:
x

array([25,  2,  5])

In [14]:
(25**2 + 2**2 + 5**2)

654

In [15]:
np.dot(x, x)

654

## Max Norm

Max Norm은 각 요소의 절대값을 취해 각각의 요소 중 최대값을 리턴하는 Norm 입니다.

In [16]:
x

array([25,  2,  5])

In [17]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Generalized Lp Norm

위에서 다룬 L1, L2, Squared L2, Max Norm 등 모든 노름은 일반화된 Lp 노름의 구체적인 경우입니다.

만약 L2 Norm을 구하고 싶다면 2대신 p를 넣고 계산해보면 L2 Norm과 같은 결과를 가져옵니다.

이 p값은 몇가지 제한 사항이 있습니다.

- 실수여야 함
- 1보다 크거나 같아야 함
- 특히 L1, L2 노름은 객체의 함수를 규칙화하기 위해 사용됨

위에서 말하고자 하는 부분은 이 Lp Norm은 매우 구체적이기도 하고 머신러닝에서 아주 흔한 활용 케이스라는 것입니다.