## Matrix Tensor

행렬표기법과 넘파이, 텐서플로우, 파이토치를 활용해 2차원 텐서인 행렬을 생성해보는 예제로 학습합니다.

행렬은 보통 대문자, Italic체, Bold체로 표기합니다.

행렬에서 차원을 표기하려 한다면 너비보다 높이를 우선시 해야 합니다.[N(row), N(col)]

In [22]:
import numpy as np

X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [23]:
# 행렬 확인
X.shape

(3, 2)

In [24]:
# 배열의 총 요소 개수
X.size

6

In [25]:
# 모든 행(':')의 첫번쨰 열('0') 선택
X[:,0]

array([25,  5,  3])

In [26]:
# 두번쨰 행('1')의 모든 열(':') 선택
X[1,:]

array([ 5, 26])

In [27]:
# 행과 열의 범위를 지정해 슬라이싱
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

## Matrix in Pytorch & Tensorflow

In [28]:
import torch
import tensorflow as tf

In [29]:
# Pytorch
X_pt = torch.tensor(X)
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]], dtype=torch.int32)

In [30]:
X_pt.shape

torch.Size([3, 2])

In [31]:
X_pt[1,:]

tensor([ 5, 26], dtype=torch.int32)

In [32]:
# Tensorflow
X_tf = tf.Variable(X)
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [33]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [34]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [35]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>