## Higher Rank Tensor (고차원 텐서)

스칼라나 벡터, 행렬을 넘어 보통 텐서를 표기할 때 **대문자 Bold, Italic, sans serif**체를 사용해 표기합니다.

예를 들어 4차원 텐서 X가 있다면 텐서 i,j,k,l 위치의 요소는 X 뒤에 아래 첨자로 (i,j,k,l) 이라고 표기됩니다.

<br>

아래 예시의 4차원 텐서는 최근 머신러닝 구조에서 매우 자주 쓰이는 텐서입니다.

보통 머신 비전 모델에 있어 매우 자주 입력값과 텐서 입력이 발생하며 이떄가 주로 4차원인 경우입니다.

따라서 이미지는 보통 4차원이고, 그 4차원은 보통 i,j,k,l로 대두됩니다.

- 이 i,j,k,l은 연습용 배치(모델의 가중치를 한번 업데이트 할 떄 사용되는 샘플의 집합) 이미지이고 값으로는 무엇이 와도 상관없습니다.
- 이번 예시에서는 32개의 이미지가 주어졌다고 가정합니다.
- 2번쨰 차원은 픽셀로 환산한 이미지의 높이를 의미합니다. (hello world 같은 머신 비전의 데이터셋 과 같음, 여기선 [MNIST](http://yann.lecun.com/exdb/mnist/) 데이터셋 사용)
- 그 이미지들은 28 픽셀의 높이와 너비를 가지고 있다고 가정합니다.
- 4번째 차원은 색상 주파수의 숫자가 됩니다.

<br>

위 MNIST 데이터셋의 이미지는 단색의 이미지 데이터셋 입니다. (흑백)

따라서 단일 색상 주파수를 필요로 하지만 보통 풀 컬러 이미지를 자주 보게 되는데 이 때는 RGB의 삼원색이 필요합니다.

지금은 따로 데이터셋을 로드해서 개별 케이스를 훑어보지는 않고 4차원 텐서 여러개를 위 케이스에 맞게 Pytorch, Tensorflow로 만들어 보기만 할 겁니다.

In [8]:
import torch
import tensorflow as tf

In [9]:
# Pytorch
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [10]:
# Tensorflow
images_tf = tf.zeros([32, 28, 28, 3])
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

위 값들은 전부 0으로 초기화 시켜 생성했지만, 실제 모델에서는 각 이미지의 픽셀 값으로 치환될겁니다.